version: "3.6"
services:

  civicrm:
    build:
      context: civicrm
      args:
        BUILDKIT_UID: 1000
        # BUILDKIT_GID: 1001 # By default, this will be the same as the UID
    hostname: civicrm
    environment:
      TERM: xterm-color
      APACHE_RUN_USER: buildkit
      VIRTUAL_HOST: dmaster.localhost
      VIRTUAL_PORT: 7979
      VIRTUAL_PROTO: http

    links:
      - database
      - redis
    depends_on: [database]
    ports:
      - "7979:7979"
      - "8000:8000"
    volumes:
      - buildkit:/buildkit/civicrm-buildkit
      - ./build:/buildkit/build
      - ./extra:/extra
      - drupal-settings /etc/drupal-settings.d
      - amp:/buildkit/.amp
      - bower-cache:/buildkit/.cache/bower
      - composer-cache:/buildkit/.composer
      - drush-cache:/buildkit/.drush
      - npm-cache:/buildkit/.npm
      - git-cache:/buildkit/app/tmp/git-cache
    restart: unless-stopped

  database:
    image: mariadb:10.4
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33306:3306"
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    links:
      - database
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: buildkit
    restart: unless-stopped

  maildev:
    image: djfarrelly/maildev
    ports:
      - "8082:80"
    restart: unless-stopped

  redis:
    image: redis:5.0-buster
    container_name: redis

    volumes:
      - qdata/:/data

    command: [ "redis-server", "--appendonly", "yes" ]

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./docker-compose-certs:/etc/nginx/certs
      - ./vhost.d /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro


  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

volumes:
  amp:
  bower-cache:
  composer-cache:
  drush-cache:
  git-cache:
  npm-cache:
  mysql:
  qdata:
  buildkit:
  drupal-settings:
