version: "3.6"
services:

  civicrm:
    build:
      context: civicrm
      args:
        BUILDKIT_UID: 1000
        # BUILDKIT_GID: 1001 # By default, this will be the same as the UID
    hostname: civicrm
    environment:
      TERM: xterm-color
      APACHE_RUN_USER: buildkit
    links:
      - database
      - redis
    depends_on: [database]
    ports:
      - "7979:7979"
      - "8000:8000"
    volumes:
      - buildkit:/buildkit/civicrm-buildkit
      - ./build:/buildkit/build
      - ./extra:/extra
      - ./drupal-settings:/etc/drupal-settings.d
      - ./civicrm-settings:/etc/civicrm-settings.d
      - amp:/buildkit/.amp
    restart: unless-stopped

  database:
    image: mariadb:10.4
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: buildkit
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "33306:3306"
    restart: unless-stopped

  maildev:
    image: djfarrelly/maildev
    ports:
      - "8082:80"
    restart: unless-stopped

  redis:
    image: redis:5.0-buster
    container_name: redis

    volumes:
      - qdata/:/data

    command: [ "redis-server", "--appendonly", "yes" ]

volumes:
  amp:
  mysql:
  qdata:
  buildkit:
  drupal-settings:
